name: Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    env:
      MIX_ENV: test
      CI: "true"
      AUTH_USER: admin
      AUTH_PASS: admin
      DATABASE_PASS: postgres
      DATABASE_USER: postgres
      DATABASE_HOST: localhost
    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: megalithic_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          elixir-version: '1.14.2'
      - run: mix deps.get --only test
      - run: mix compile --warnings-as-errors
      - run: mix test
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
