name: Tests

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    env:
      MIX_ENV: test
      CI: "true"
      AUTH_USER: admin
      AUTH_PASS: admin
      DATABASE_PASS: postgres
      DATABASE_USER: postgres
      DATABASE_HOST: localhost
    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: megalithic_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '25'
        elixir-version: '1.14.2'
    - run: mix deps.get
    - run: mix compile --force --warnings-as-errors
    - run: mix test
